- clean: ['~', '~/.config', '~/.atom']

- link:
    ~/.dotfiles: ''
    ~/.bashrc: bashrc
    ~/.gitconfig: gitfiles/gitconfig
    ~/.gitignore: gitfiles/gitignore
    ~/.gitattributes: gitfiles/gitattributes
    ~/.hushlogin: hushlogin
    ~/.screenrc: screenrc
    ~/.zsh: zsh/
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/keymap.cson:
        create: true
        path: atom/keymap.cson
    ~/.atom/snippets.cson:
        create: true
        path: atom/snippets.cson
    ~/.atom/styles.less:
        create: true
        path: atom/styles.less

- shell:
    - [git update-submodules, Installing submodules]
