- clean: ['~', '~/.config', '~/.atom']

- link:
    ~/.dotfiles: ''
    ~/.bashrc: bashrc
    # ~/.zsh: zsh
    # ~/.emacs: emacs
    ~/.gitfiles: gitfiles
    ~/.gitconfig: gitfiles/gitconfig
    ~/.hushlogin: hushlogin
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/keymap.cson:
        create: true
        path: atom/keymap.cson
    ~/.atom/snippets.cson:
        create: true
        path: atom/snippets.cson
    ~/.atom/styles.less:
        create: true
        path: atom/styles.less

- shell:
    - [git update-submodules, Installing submodules]
