- clean: ['~', '~/.config', '~/.atom']

- link:
    ~/.dotfiles: ''
    ~/.bashrc: bashrc
    ~/.gitfiles: gitfiles
    ~/.gitconfig: gitfiles/gitconfig
    ~/.hushlogin: hushlogin
    ~/.screenrc: screenrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/config.cson:
        create: true
        path: atom/config.cson
    ~/.atom/keymap.cson:
        create: true
        path: atom/keymap.cson
    ~/.atom/snippets.cson:
        create: true
        path: atom/snippets.cson
    ~/.atom/styles.less:
        create: true
        path: atom/styles.less
    ~/.config/powerline:
        create: true
        path: config/powerline/
    ~/Library/Application Support/Code/User/keybindings.json:
        create: true
        path: vscode/keybindings.json
    ~/Library/Application Support/Code/User/settings.json:
        create: true
        path: vscode/settings.json
    ~/Library/Application Support/Code/User/snippets:
        create: true
        path: vscode/snippets

- shell:
    - [git update-submodules, Installing submodules]
