- clean: ['~']

- link:
    ~/.bashrc: bashrc
    ~/.zsh: zsh
    ~/.emacs: emacs
    ~/.dotfiles: ''
    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
